version: '3.8'

services:
  web:
    build: ./web
    command: gunicorn --bind 0.0.0.0:5000 app:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPassword
      - POSTGRES_DB=postgresDbProd

volumes:
  postgres_data_prod: