version: '3.8'

services:
  web:
    build: ./web
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: pgadmin_db_lundiMatin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres_data:

